[package]
name = "tarkov-stash-console"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
spinners = "4.1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
